const sentences = {
  easy: [
    "The sun sets in the west every evening, painting the sky with beautiful colors.",
    "I enjoy reading books and spending time with my friends and family.",
    "She sings melodious songs that touch the hearts of everyone who listens.",
    "The cat chased the playful mouse around the room with great excitement.",
    "My favorite color is blue, and I love to go swimming in the sparkling sea.",
    "We had a delicious dinner together, filled with laughter and joyous moments.",
    "The flowers in the garden bloom in vibrant colors, creating a stunning sight.",
    "He is a talented artist, creating breathtaking paintings that amaze everyone.",
    "They built a sandcastle on the beach, using shells as decorations on top.",
    "Running in the park and feeling the fresh breeze energizes me every morning.",
    "The friendly dog wagged its tail and greeted everyone with a big smile.",
    "The sweet aroma of freshly baked cookies filled the entire kitchen.",
    "I like to play soccer with my friends at the park on weekends.",
    "The little girl giggled as she blew bubbles into the air on a sunny day.",
    "We sat around the campfire, sharing stories and roasting marshmallows.",
  ],
  medium: [
    "The majestic mountains stood tall, covered in a blanket of snow, glistening in the sunlight.",
    "The bustling city streets were filled with people, cars, and the sound of honking horns.",
    "As the rain poured down, the children splashed in puddles and laughed with delight.",
    "She gazed at the starry night sky, marveling at the beauty of the universe above.",
    "The old oak tree provided shade on hot summer days, offering a peaceful retreat.",
    "In the distance, a gentle breeze rustled the leaves, creating a soothing melody.",
    "The ancient castle held many secrets, hidden within its walls for centuries.",
    "He took a deep breath, closed his eyes, and let the waves of calmness wash over him.",
    "The charming little cottage was surrounded by colorful flowers and a picket fence.",
    "The delicious aroma of freshly baked bread filled the cozy bakery.",
    "The curious cat explored every nook and cranny of the mysterious old house.",
    "The train chugged along the tracks, passing through picturesque countryside.",
    "The adventurous explorers set out on a quest to find the lost treasure of the desert.",
    "The shimmering moonlight illuminated the path through the dark forest.",
    "With a paintbrush in hand, she created a masterpiece on the canvas, expressing her emotions.",
  ],
  hard: [
    "The relentless storm battered the ship, causing it to sway violently on the rough, unforgiving sea.",
    "The intricate labyrinth of tunnels and passages made it nearly impossible to find the hidden treasure.",
    "The daunting challenge of climbing the towering mountain tested their strength and determination.",
    "In the depths of the ancient ruins, they discovered a mysterious artifact with unknown powers.",
    "The complex mathematical equations required deep concentration and precise calculations.",
    "With every step, the quicksand threatened to engulf them, making their escape even more perilous.",
    "The sophisticated AI system analyzed vast amounts of data to predict future trends accurately.",
    "The haunting melody of the piano echoed through the grand concert hall, captivating the audience.",
    "In the dimly lit dungeon, they searched for the key to unlock the secret door.",
    "The elegant ballroom was adorned with crystal chandeliers, creating a dazzling display of light.",
    "The elite team of scientists worked tirelessly to decipher the ancient hieroglyphs on the stone tablet.",
    "The intricate dance routine required precision and synchronization among the performers.",
    "The enigmatic riddles and puzzles challenged their intellect and problem-solving skills.",
    "The marathon runners endured grueling hours of training to prepare for the demanding race.",
    "In the heart of the dense jungle, they encountered rare and elusive species of wildlife.",
  ],
};

export default sentences;
